### ISSUE TITLE
keychains

### ISSUE THREAD

**Issue by MichaelXavier** [crystalcommerce/cc-cli#1]
Keychains should probably be named to columns, since you specify the ones you want with --cols. The word keychain doesn't make much sense.

As per the docs, for descriptors we should not show them a static list but rather something like `descriptors.*` as they vary category by category.

**Comment by neilmarion** [comment]
Ok. I'll fix this issu first before we publish.

**Comment by neilmarion** [comment]
https://github.com/crystalcommerce/cc-cli/commit/5f66bf7e4a90d451ea8e23c0a626c71e4b5f9130 solving this issue.
